'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { ArrowRight, Eye, Sparkles, TrendingUp } from 'lucide-react';

export default function PublicReportPage() {
  const params = useParams();
  const router = useRouter();
  const token = params.token as string;
  
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchReport();
  }, [token]);

  const fetchReport = async () => {
    try {
      const response = await fetch(`/api/public/report/${token}`);
      
      if (!response.ok) {
        throw new Error('Report not found');
      }

      const data = await response.json();
      setReport(data);
    } catch (err) {
      setError('Report not found or no longer available');
    } finally {
      setLoading(false);
    }
  };

  const handleSignUp = () => {
    // Store referral token in localStorage
    localStorage.setItem('referral_token', token);
    router.push('/signup');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Loading report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center max-w-md">
          <div className="text-6xl mb-4">📊</div>
          <h1 className="text-2xl font-bold mb-2">Report Not Found</h1>
          <p className="text-muted-foreground mb-6">
            This report may have been removed or is no longer publicly available.
          </p>
          <Button onClick={() => router.push('/')}>
            Go to Homepage
          </Button>
        </div>
      </div>
    );
  }

  const showWatermark = report.plan === 'starter';

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="bg-primary/10 rounded-lg p-2">
                <TrendingUp className="h-6 w-6 text-primary" />
              </div>
              <div>
                <h1 className="text-lg font-bold">Performance Report</h1>
                <p className="text-sm text-muted-foreground">
                  {report.client_name} • Generated by {report.agency_name}
                </p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Eye className="h-4 w-4" />
                <span>{report.public_views} views</span>
              </div>
              <Button onClick={handleSignUp} size="lg">
                <Sparkles className="mr-2 h-4 w-4" />
                Create Your Own
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Report Content */}
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          {/* Report HTML */}
          <div 
            className="bg-card rounded-lg border border-border p-8 shadow-lg"
            dangerouslySetInnerHTML={{ __html: report.report_data.html }}
          />

          {/* CTA Section */}
          <div className="mt-12 bg-gradient-to-r from-primary/10 via-purple-500/10 to-pink-500/10 rounded-lg border border-primary/20 p-8 text-center">
            <div className="max-w-2xl mx-auto">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/20 mb-6">
                <Sparkles className="h-8 w-8 text-primary" />
              </div>
              
              <h2 className="text-3xl font-bold mb-4">
                Want AI-Powered Reports Like This?
              </h2>
              
              <p className="text-lg text-muted-foreground mb-6">
                Generate professional client reports in minutes, not hours. 
                Join {report.agency_name} and hundreds of agencies using AgencyOS AI.
              </p>

              <div className="grid md:grid-cols-3 gap-4 mb-8">
                <div className="bg-background/50 backdrop-blur-sm rounded-lg p-4 border border-border/50">
                  <div className="text-3xl font-bold text-primary mb-1">2 min</div>
                  <div className="text-sm text-muted-foreground">Report Generation</div>
                </div>
                <div className="bg-background/50 backdrop-blur-sm rounded-lg p-4 border border-border/50">
                  <div className="text-3xl font-bold text-primary mb-1">AI-Powered</div>
                  <div className="text-sm text-muted-foreground">Insights & Analysis</div>
                </div>
                <div className="bg-background/50 backdrop-blur-sm rounded-lg p-4 border border-border/50">
                  <div className="text-3xl font-bold text-primary mb-1">Free</div>
                  <div className="text-sm text-muted-foreground">Trial Available</div>
                </div>
              </div>

              <Button onClick={handleSignUp} size="lg" className="text-lg px-8 py-6">
                Start Free Trial
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>

              <p className="text-sm text-muted-foreground mt-4">
                No credit card required • Setup in 5 minutes
              </p>
            </div>
          </div>

          {/* Watermark for Starter Plan */}
          {showWatermark && (
            <div className="mt-8 text-center">
              <div className="inline-flex items-center gap-2 px-6 py-3 bg-primary/10 border border-primary/20 rounded-full">
                <span className="text-primary font-semibold">⚡ Powered by AgencyOS AI</span>
                <span className="text-muted-foreground">•</span>
                <button 
                  onClick={handleSignUp}
                  className="text-primary hover:underline font-medium"
                >
                  Create your own reports
                </button>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border mt-16 py-8">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          <p>© 2024 AgencyOS AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
